# Generated by Django 5.1.6 on 2025-02-16 03:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the podcast episode', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the episode')),
                ('link', models.URLField(blank=True, help_text='Link to the episode (e.g. on another platform)', null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally Unique Identifier', unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the episode was published')),
                ('enclosure_url', models.URLField(help_text='URL of the audio file', max_length=255)),
                ('enclosure_length', models.IntegerField(blank=True, help_text='Length of the audio file in bytes', null=True)),
                ('enclosure_type', models.CharField(default='audio/mpeg', help_text='Content type of the audio file', max_length=50)),
                ('duration', models.CharField(blank=True, help_text="Duration of the audio (e.g., '1:30:00')", max_length=20, null=True)),
                ('explicit', models.BooleanField(default=False, help_text='Is the content explicit?')),
                ('image', models.ImageField(blank=True, help_text='Episode artwork', null=True, upload_to='podcast_images/')),
                ('podcast_title', models.CharField(help_text="Title of the podcast channel (e.g., 'David's Declared Space')", max_length=255)),
                ('podcast_description', models.TextField(help_text='Description of the podcast channel')),
                ('podcast_link', models.URLField(help_text='Link to the podcast channel')),
                ('managing_editor', models.EmailField(blank=True, help_text='Managing editor email', max_length=254, null=True)),
                ('web_master', models.EmailField(blank=True, help_text='Web master email', max_length=254, null=True)),
                ('language', models.CharField(default='en-us', help_text="Language of the podcast (e.g., 'en-us')", max_length=10)),
                ('copyright_info', models.CharField(blank=True, help_text='Copyright information', max_length=255, null=True)),
                ('itunes_author', models.CharField(blank=True, help_text='iTunes author', max_length=255, null=True)),
                ('itunes_owner_name', models.CharField(blank=True, help_text='iTunes owner name', max_length=255, null=True)),
                ('itunes_owner_email', models.EmailField(blank=True, help_text='iTunes owner email', max_length=254, null=True)),
                ('itunes_image', models.ImageField(blank=True, help_text='iTunes channel artwork', null=True, upload_to='podcast_channel_images/')),
                ('itunes_category', models.CharField(blank=True, help_text='iTunes category', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
