# Generated by Django 5.1.6 on 2025-02-18 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the podcast channel', max_length=255)),
                ('description', models.TextField(help_text='Description of the podcast channel')),
                ('link', models.URLField(help_text='Link to sit of the podcast channel')),
                ('managing_editor', models.EmailField(help_text='Managing editor email', max_length=254)),
                ('web_master', models.EmailField(help_text='Web master email', max_length=254)),
                ('copyright_info', models.CharField(help_text='Copyright information', max_length=255)),
                ('author', models.CharField(help_text='author name', max_length=255)),
                ('owner_name', models.CharField(help_text='owner name', max_length=255)),
                ('owner_email', models.EmailField(help_text='owner email', max_length=254)),
                ('category', models.CharField(help_text='iTunes category', max_length=255)),
                ('artwork', models.ImageField(help_text='add artwork', upload_to='channel_artwork')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the podcast episode', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the episode')),
                ('link', models.URLField(help_text='Link to site of podcast')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated GUId', unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the episode was published')),
                ('duration', models.CharField(blank=True, help_text="Duration of the audio (e.g., '1:30:00')", max_length=20, null=True)),
                ('explicit', models.BooleanField(default=False, help_text='Is the content explicit?')),
                ('file_length', models.IntegerField(blank=True, help_text='Length of the audio file in bytes', null=True)),
                ('file_type', models.CharField(default='audio/mpeg', help_text='Content type of the audio file', max_length=50)),
                ('file', models.FileField(help_text='add audio', upload_to='episodes_audio/')),
                ('artwork', models.ImageField(help_text='add artwork', upload_to='episode_artwork/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcastchannel')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
