# Generated by Django 5.1.6 on 2025-02-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcastchannel_podcastepisode_delete_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastchannel',
            name='category',
            field=models.CharField(help_text='use categories that itunes likes', max_length=255),
        ),
    ]
