# Generated by Django 5.1.6 on 2025-02-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_podcastchannel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcastchannel'),
        ),
    ]
