# Generated by Django 5.1.6 on 2025-02-18 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_alter_podcastepisode_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastchannel',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the episode was published'),
        ),
    ]
