# Generated by Django 5.1.6 on 2025-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='explicit',
        ),
        migrations.AddField(
            model_name='podcastchannel',
            name='explicit',
            field=models.BooleanField(default=False, help_text='Is the content explicit?'),
        ),
        migrations.AddField(
            model_name='podcastchannel',
            name='language',
            field=models.CharField(choices=[('en-us', 'English (US)')], default='en-us', help_text='language of the podcast', max_length=8),
        ),
        migrations.AlterField(
            model_name='podcastchannel',
            name='artwork',
            field=models.ImageField(help_text='add artwork', upload_to='channel_artwork/'),
        ),
        migrations.AlterField(
            model_name='podcastchannel',
            name='link',
            field=models.URLField(help_text='Link to the podcast channel site'),
        ),
    ]
