# Generated by Django 5.1.6 on 2025-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_remove_podcastepisode_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastchannel',
            name='category',
            field=models.CharField(choices=[('arts', 'arts'), ('business', 'busines'), ('comedy', 'comedy'), ('education', 'education'), ('fiction', 'fiction'), ('government', 'government'), ('history', 'history'), ('kids & family', 'kids & family'), ('leisure', 'leisure'), ('music', 'music'), ('religion & spirituality', 'religion & spirituality'), ('science', 'science'), ('society & culture', 'society & culture'), ('sports', 'sports'), ('technology', 'technology'), ('true crime', 'true crime'), ('tv & film', 'tv & film')], default='fiction', help_text='use categories that itunes likes', max_length=255),
        ),
    ]
